module.exports = {
  // Note: rootDir is relative to the directory containing this file.
  rootDir: './src',
  setupFiles: [
    // '../setup.js',
  ],
  testPathIgnorePatterns: [
    // '<rootDir>/xcoobee/api/ApiAccessTokenCache.spec.js',
    // '<rootDir>/xcoobee/api/ApiUtils.spec.js',
    // '<rootDir>/xcoobee/api/BeesApi.spec.js',
    // '<rootDir>/xcoobee/api/CampaignApi.spec.js',
    // '<rootDir>/xcoobee/api/ConsentsApi.spec.js',
    // '<rootDir>/xcoobee/api/ConversationsApi.spec.js',
    // '<rootDir>/xcoobee/api/DirectiveApi.spec.js',
    // '<rootDir>/xcoobee/api/EndpointApi.spec.js',
    // '<rootDir>/xcoobee/api/EndpointUtils.spec.js',
    // '<rootDir>/xcoobee/api/EventsApi.spec.js',
    // '<rootDir>/xcoobee/api/EventSubscriptionsApi.spec.js',
    // '<rootDir>/xcoobee/api/FileApi.spec.js',
    // '<rootDir>/xcoobee/api/InboxApi.spec.js',
    // '<rootDir>/xcoobee/api/PolicyApi.spec.js',
    // '<rootDir>/xcoobee/api/TokenApi.spec.js',
    // '<rootDir>/xcoobee/api/UsersApi.spec.js',
    // '<rootDir>/xcoobee/api/UsersCache.spec.js',
    // '<rootDir>/xcoobee/core/EncryptionUtils.spec.js',
    // '<rootDir>/xcoobee/core/XcooBeeError.spec.js',
    // '<rootDir>/xcoobee/sdk/Config.spec.js',
    // '<rootDir>/xcoobee/sdk/ConfigUtils.spec.js',
    // '<rootDir>/xcoobee/sdk/SdkUtils.spec.js',
  ],
};
